version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proyecto
    ports:
      - "5432:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data

volumes:
  postgres_storage:
    driver: local
