version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proyecto
    ports:
      - "5432:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - backend-net

  backend:
    build:
      context: .
    image: integrador-backend
    container_name: backend_app
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - backend-net
    environment:
      DB_URL: jdbc:postgresql://db:5432/proyecto
      DB_PORT: 5432
      DB_NAME: proyecto
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_storage:

networks:
  backend-net:
    driver: bridge
