services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      POSTGRES_DB: proyecto
    ports:
      - "5432:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data
 